service: gateway

provider:
  stackName: "${self:custom.stage}-${self:service}"
  name: aws
  deploymentBucket:
    name: ${self:custom.env.bucketName}

resources:
  Resources:
    SharedApiGateway:
      Type: AWS::ApiGateway::RestApi 
      Properties:
        Name: "${self:custom.env.gatewayName}"
    HelloPath: 
      Type: AWS::ApiGateway::Resource 
      Properties:
        RestApiId: 
          Ref: SharedApiGateway
        ParentId: 
          Fn::GetAtt: 
            - SharedApiGateway
            - RootResourceId
        PathPart: hello
    HelloReadEndPoint:
      Type: AWS::ApiGateway::Method
      Properties:
        AuthorizationType: NONE
        HttpMethod: GET
        Integration: 
          IntegrationHttpMethod: POST
          Type: AWS
          Uri: 
            !Join
              - ':'
              - - 'arn:aws:apigateway'
                - Ref: 'AWS::Region'
                - lambda:path/2015-03-31/functions/arn:aws:lambda
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - function
                - !Join 
                    - ''
                    - - '$'
                      - '{stageVariables.getHelloFunction}/invocations'
          PassthroughBehavior: WHEN_NO_TEMPLATES
          IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ''
          RequestTemplates:
            "application/json": "{
                \"body\" : $input.json('$'),
                \"headers\": {
                  #foreach($header in $input.params().header.keySet())
                  \"$header\": \"$util.escapeJavaScript($input.params().header.get($header))\" #if($foreach.hasNext),#end
                  #end
                },
                \"method\": \"$context.httpMethod\",
                \"params\": {
                  #foreach($param in $input.params().path.keySet())
                  \"$param\": \"$util.escapeJavaScript($input.params().path.get($param))\" #if($foreach.hasNext),#end
                  #end
                },
                \"query\": {
                  #foreach($queryParam in $input.params().querystring.keySet())
                  \"$queryParam\": \"$util.escapeJavaScript($input.params().querystring.get($queryParam))\" #if($foreach.hasNext),#end
                  #end
                }  
              }"
        MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty
        ResourceId: 
          Ref: HelloPath
        RestApiId: 
          Ref: SharedApiGateway

custom:
  env: ${file(./${opt:env, 'dev'}.yml)}
  stage: ${opt:stage, 'hello-test'}